### ISSUE TITLE
회원 가입/로그인/로그아웃 구현

### ISSUE THREAD

**Issue by gidskql6671** [JaeMyeongSon/KNU-AI-BACKEND#3]
### 회원가입
- [x] 회원 가입 기능의 구현
  - User ID 없이 이메일/패스워드 체재로 가용
- [x] 이메일 양식 검사
- [x] 이메일 중복 검사 
### 로그인
- [ ] 로그인
- [x] cookie-parser 문제 해결하기&꼭 써야하나..? 다시 공부
### 로그아웃

**Comment by oyoungsun** [comment]
- cookie parser 문제 해결
- login 시도 시 
- [Nest] 7872  - 2023. 10. 03. 오후 10:26:22   ERROR [ExceptionsHandler] Failed to serialize user into session

<img width="575" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/ac9b7c0e-7a78-4949-becd-d254a1ca23b0">
