### ISSUE TITLE
로깅 인프라 구축

### ISSUE THREAD

**Issue by gidskql6671** [JaeMyeongSon/KNU-AI-BACKEND#5]
## 구현 사항
- MongoDB를 사용하여 로그를 기록할 수 있는 환경 구축
   - [x] @nestjs/common의 LoggerService 구현하기
   - [x] this.logger.. 호출 시 MongoDB에 로직 json저장하는 로직 작성
   - [ ]  console.log를 로거로 대체
- [ ] 로그로 남길 필요가 있는 정보 산정
- [ ] 로깅을 위한 Interceptor, Exception Filter 등을 구현

참고자료
[29CM 로깅 인프라,,](https://medium.com/29cm/29cm-%EB%A1%9C%EA%B7%B8-%EC%88%98%EC%A7%91-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%86%8C%EA%B0%9C-e7955d7deec6)
자료2
[NestJS에서 로깅(logging)하기](https://www.daleseo.com/nestjs-logging/)
https://assu10.github.io/dev/2023/03/26/nest-logging/#31-nest-winston-%EC%A0%81%EC%9A%A9

**Comment by JaeMyeongSon** [comment]
https://github.com/JaeMyeongSon/KNU-AI-BACKEND/pull/35
해당 PR에서 Exception Filter를 구현해두었습니다.

**Comment by oyoungsun** [comment]
<img width="1043" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/55eb8fb9-91e6-4d9b-b85b-f8250356833f">
로그 level, 메시지, 시간 을 json형태로 저장하게 되었습니다

궁금증
- 로깅시에 MongoDB를 사용하는 이유가 궁금합니다! 연관관계 없는 데이터의 많은 저장떄문에..?

**Comment by oyoungsun** [comment]
[로깅 인프라 구축하기](https://velog.io/@oyoungsun/NestJS-%EB%A1%9C%EA%B9%85-%EC%9D%B8%ED%94%84%EB%9D%BC-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0)

velog에 구현 과정 기록했습니닷
